### PR TITLE
Read SVG from ByteString

### PR DESCRIPTION
**Pull request by igormoreno**
Summary: Add function to read SVG from a Lazy ByteString.

Ps.: Hi. I've made this small change I needed and I figured it wasn't "worthy" of a pull request but I guess it makes more sense to ask you if you think this change is useful or not.

### CODE REVIEW

**Comment by byorgey** [comment]
Sure, why not?  Thanks!

**Comment by byorgey** [comment]
Released `diagrams-input-0.1.2` to Hackage.

**Comment by igormoreno** [comment]
The function I added ended up being removed in the next commit:
https://github.com/diagrams/diagrams-input/commit/f941bf9cb61788aa96e463be892076c77eab2eea#diff-2e86bd6913aa75f4cf8fde9f092fb606d7f6a24e2ad97290194476453a450552
Maybe the author was working on an older version of the file before this pull request was merged.

**Comment by tkvogt** [comment]
Sorry. I did this. Can you make the pull request again?

**Comment by igormoreno** [comment]
Sure :-)

**Pull request merged**
